exclude: |
    (?x)(
        docs/conf.py
    )
repos:
#  - repo: git://github.com/pre-commit/pre-commit-hooks
#    rev: v2.2.3
#    hooks:
#      - id: trailing-whitespace
#      - id: check-added-large-files
#        args: ['--maxkb=1700']
#      - id: check-ast
#      - id: check-json
#      - id: check-merge-conflict
#      - id: check-xml
#      - id: check-yaml
#      - id: debug-statements
#      - id: end-of-file-fixer
#      - id: requirements-txt-fixer
#      - id: mixed-line-ending
#        args: ['--fix=auto']
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.4
    hooks:
      - id: autopep8
        args: ['--in-place', '--aggressive', '--aggressive', '--recursive', '--max-line-length=100', '--ignore=E501,E402,W503,W504,E731']
  - repo: https://github.com/humitos/mirrors-autoflake.git
    rev: v1.3
    hooks:
      - id: autoflake
        args: ['--in-place', '--recursive', '--remove-all-unused-imports', '--remove-unused-variable', '--ignore-init-module-imports']
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        args: ['--ignore=E501,E402,W503,W504,E731,F401']
